### ISSUE TITLE
How to properly set the Custom position for CalloutView?

### ISSUE THREAD

**Issue by hemangshah** [okhanokbay/MapViewPlus#1]
```
func mapView(_ mapView: MapViewPlus, centerForCalloutViewOf annotationView: AnnotationViewPlus) -> CalloutViewPlusCenter {
        return .customCenter(self.mapViewPlus.center)
    }
```

With the current code, it's not working. Even I tried with other values too but it's not working.

**Comment by okhanokbay** [comment]
I just confirmed it's working. Did you set the `calloutViewCustomizerDelegate` of MapViewPlus? @hemangshah

**Comment by hemangshah** [comment]
It's going inside the delegate method but then it's not coming at the right place for me. @okhanokbay

Thanks for the quick response.

**Comment by okhanokbay** [comment]
In the example project's BasicCalloutView class, I added:

```
extension BasicCalloutView: CalloutViewCustomizerDelegate {
  func mapView(_ mapView: MapViewPlus, boundsForCalloutViewOf annotationView: AnnotationViewPlus) -> CalloutViewPlusBound {
    return .defaultBounds
  }
	
  func mapView(_ mapView: MapViewPlus, centerForCalloutViewOf annotationView: AnnotationViewPlus) -> CalloutViewPlusCenter {
    return .customCenter(CGPoint(x: 30, y: -200))
  }
}
```

Also, in the example project's BasicExampleViewController class, added:

`mapView.anchorViewCustomizerDelegate = self` **into** `override func viewDidLoad()` method

`mapView.calloutViewCustomizerDelegate = calloutView` **into** `func mapView(_ mapView: MapViewPlus, calloutViewFor annotationView: AnnotationViewPlus) -> CalloutViewPlus` method

Can you please try this way? Or you can share an example project that demonstrates the problem you are facing and I can try to help. @hemangshah

**Comment by okhanokbay** [comment]
Please re-open if there is anything else about this issue.

**Comment by hemangshah** [comment]
Hi @okhanokbay, I still don't understand how `CalloutViewPlusCenter` is working? See if I want to show the CalloutView to self.view.frame.size.height - (tabbarHeight + margin + calloutViewHeight) then it should show at that place, right?

The values are as follows: tabbarHeight = 50.0, margin = 20.0, and calloutViewHeight = 100.0

**Comment by hemangshah** [comment]
I noticed that it is not displaying (showing) the CalloutView based on the above value. But instead, it is displaying it based on the annotation position on the map. To understand this, I will add some screenshots here, FYR.

**Comment by okhanokbay** [comment]
Yes, it's altering the center of callout view related to annotation view, not related to view or map view itself. @hemangshah

**Comment by hemangshah** [comment]
Ok, thanks for your quick reply @okhanokbay, Can I show my own view when annotation will be selected? Instead of showing a custom call out?

**Comment by okhanokbay** [comment]
You can return any UIView subclass (also must conform to `CalloutViewPlus` protocol) from `calloutViewForAnnotationView`

**Comment by hemangshah** [comment]
@okhanokbay, sorry, I think, you have misunderstood this for that I have raised another issue which you can check. My own view means (not in a form of an annotation) instead I want it to be displayed in `self.view`.

**Comment by okhanokbay** [comment]
Is it #4 ? @hemangshah

**Comment by hemangshah** [comment]
@okhanokbay, Yes!
