### ISSUE TITLE
How to use My own custom Pin and Callout view of Mapview Plus?

### ISSUE THREAD

**Issue by hadwanihardik** [okhanokbay/MapViewPlus#11]
I want to change annotation view and use my own custom annotation view and Call out as per shown by you. Can I do this?

**Comment by asar1** [comment]
comment out the this delegate `func mapView(_ mapView: MapViewPlus, imageFor annotation: AnnotationPlus) -> UIImage?` in MapViewPlusDelegate class,
and write this
 `let anno = annotation as! AnnotationPlus
        annotationView?.image = anno.image`
in "extension MapViewPlus: MKMapViewDelegate"
make a variable in AnnotationPlus of type UIImage, and pass it into this class init()
and set your annotation e.g 
`let annotation = AnnotationPlus(viewModel: viewModel, coordinate: CLLocationCoordinate2DMake(latitude, longitude), image: your image name)`

**Comment by okhanokbay** [comment]
You can return any custom view as callout view but you can't use a custom view as annotation view. You can only use your own image as annotation view.

**Comment by hadwanihardik** [comment]
In this way I was able to add customview. but How can I get tap event on this custom callout?

**Comment by okhanokbay** [comment]
You can add a `UITapGestureRecognizer` to your custom view and bind the delegate callbacks of this view to any desired destination.
