### ISSUE TITLE
How to hide callout?

### ISSUE THREAD

**Issue by hadwanihardik** [okhanokbay/MapViewPlus#12]
Once Call out is visible , I want to hide call out if user clicks it again. 
Right now  once callout is open we can not hide or remove it.

**Comment by okhanokbay** [comment]
Callouts are getting hidden/removed when you tap outside of them right now, do you want to make them hidden when you tap on them?

**Comment by hadwanihardik** [comment]
YEs

**Comment by hadwanihardik** [comment]
I resolved this. Closing it.

**Comment by hadwanihardik** [comment]
Yes. I want to remove it
