### ISSUE TITLE
unable to compile example

### ISSUE THREAD

**Issue by appsird** [okhanokbay/MapViewPlus#14]
Hi,

Thanks for your example. I have been unable to compile, and receive following error:

Showing Recent Messages
:-1: Multiple commands produce '/Users/brian/Library/Developer/Xcode/DerivedData/MapViewPlus-cqabsqclifgkyqgnhukrshycpcez/Build/Products/Debug-iphoneos/MapViewPlus/MapViewPlus.framework/.gitkeep':
1) Target 'MapViewPlus' (project 'Pods') has copy command from '/Users/brian/Documents/MapViewPlus/MapViewPlus/Assets/.gitkeep' to '/Users/brian/Library/Developer/Xcode/DerivedData/MapViewPlus-cqabsqclifgkyqgnhukrshycpcez/Build/Products/Debug-iphoneos/MapViewPlus/MapViewPlus.framework/.gitkeep'
2) Target 'MapViewPlus' (project 'Pods') has copy command from '/Users/brian/Documents/MapViewPlus/MapViewPlus/Classes/.gitkeep' to '/Users/brian/Library/Developer/Xcode/DerivedData/MapViewPlus-cqabsqclifgkyqgnhukrshycpcez/Build/Products/Debug-iphoneos/MapViewPlus/MapViewPlus.framework/.gitkeep'

___

I attempted to reinstall the Pod, compile the example. Tried removing derived data.

What is the process to clone the project and compile?

THanks,
Brian

**Comment by okhanokbay** [comment]
I've just tried and been able to compile the example. I've just downloaded it as a zip (you can also run  git clone in terminal or clone it in your own way) and then double clicked the xcworkspace file and run the project.

**Comment by okhanokbay** [comment]
Please delete your Derived Data folder and try again.
