### ISSUE TITLE
not working with Xcode 11

### ISSUE THREAD

**Issue by xthemadgenius** [okhanokbay/MapViewPlus#25]
Im getting errors a bunch of errors when I run this on Xcode 11 specifically in the KIngFisher Pod attached to it where it shows that I have 11 errors in its files

**Comment by okhanokbay** [comment]
Linked Kingfisher pod needs to be updated. Will do soon

**Comment by gerchicov-bp** [comment]
@okhanokbay it is still not updated

**Comment by okhanokbay** [comment]
Sorry for being tooo late 😜 It should work now 👍
