### ISSUE TITLE
Map is scrolling down 10 pixels automatically.

### ISSUE THREAD

**Issue by hemangshah** [okhanokbay/MapViewPlus#5]
Every time I select my annotation map will go down by 10 pixels. 
![mapviewplus](https://user-images.githubusercontent.com/3313412/37394448-c88818fa-2799-11e8-969c-61f77a0de4fe.gif)

**Comment by okhanokbay** [comment]
Can you please share the center point you are returning from `centerForCalloutViewOfannotationView` in this example? @hemangshah

**Comment by hemangshah** [comment]
```
    func mapView(_ mapView: MapViewPlus, centerForCalloutViewOf annotationView: AnnotationViewPlus) -> CalloutViewPlusCenter {
        let points = CGPoint(x: 30, y: 300)
        return .customCenter(points)
    }
```

**Comment by okhanokbay** [comment]
I can't reproduce this in any of the example projects. Maybe related to your implementation. If not, can you please reproduce this in one of the example projects and re-open the issue. @hemangshah

**Comment by okhanokbay** [comment]
I just accidentally reproduced this. The cause of this has no relation to MapViewPlus and can be solved easily. I will add the solution for future reference. 

If you set the constraints of MapViewPlus instance like below, you will see map scrolling down as shown above in the GIF provided by @hemangshah:

![wrong-constraints-2](https://user-images.githubusercontent.com/7668886/38119599-a1cc7c22-33cb-11e8-9bdb-e568ec36e254.png)

To solve this, you can change aligning from "Superview" to "Top Layout Guide" like below:

![correct-constraints](https://user-images.githubusercontent.com/7668886/38119514-f34c4b8c-33ca-11e8-876e-6c9fd2648601.png)

**Comment by hemangshah** [comment]
Wooho! Thanks @okhanokbay 👍
