### ISSUE TITLE
How to force hide a CalloutView using MapViewPlus?

### ISSUE THREAD

**Issue by hemangshah** [okhanokbay/MapViewPlus#6]
Can we have a new method which will hide any visible CalloutView from the Map?

`mapViewPlusObj.hideActiveCalloutView()`

**Comment by okhanokbay** [comment]
Please try `mapViewPlusObj.deselectAnnotation(annotation:animated:)`

Pass this method an instance of your `AnnotationPlus` object which you want to hide the callout of it.

@hemangshah
