### ISSUE TITLE
How to get the selected annotation?

### ISSUE THREAD

**Issue by hemangshah** [okhanokbay/MapViewPlus#7]
```
extension KiosksViewController: MapViewPlusDelegate {
    func mapView(_ mapView: MapViewPlus, calloutViewFor annotationView: AnnotationViewPlus) -> CalloutViewPlus {
        return EmptyView()
    }
}
```

As per my need, I don't want to show a CalloutView instead I will show up a View which I will add and display on `self.view`. So when I tap on any of the annotations, how would I get to know which annotation is tapped so that in my view I can update the label values from the selected annotation.

**Comment by okhanokbay** [comment]
Let's continue in #4 about this.
