### ISSUE TITLE
My custom view not get right width in iphone 5 

### ISSUE THREAD

**Issue by baysgalan19** [okhanokbay/MapViewPlus#9]

**Comment by baysgalan19** [comment]
CallOutAndAnchorView always return width = 126

**Comment by okhanokbay** [comment]
In README, this is stated as below:

> ```swift
> func mapView(_ mapView: MapViewPlus, boundsForCalloutViewOf annotationView: AnnotationViewPlus) -> CalloutViewPlusBound
> ```
> 
> - Change the bounds for callout view without changing the frames in Interface Builder. If you don't use this delegate method, then your callout view's frame will stay the same as the Interface Builder file. You can also use this to change frame dynamically according to the data in callout view!


You can either use the above delegate method to alter the width or you can change it in your own implementation. If you don't use the above method, MapViewPlus won't mess with your settings.
